### ISSUE TITLE
Running in Linux Mint 12

### ISSUE THREAD

**Issue by david-jointech** [hmarr/chromesheep#1]
hi,

I am trying to run chromesheep in Linux Mint 12 and am being confronted by various problems.
First I had to install (additionally to the ones mentioned in the README) the npm extensions jsdom and events. Installing jsdom solves the problem with the pcap_bindings error. 
In the pcap file ($YOURHOMEDIRECTORY/.node/.npm/pcap/VERSIONNUMBER/package/pcap.js) I changed this:

``` javascript
//for me at line 1345
TCP_tracker.prototype.setup_http_tracking = function (session) {
  var self = this, http = {
    request : {
      headers : {},
      url : "",
      method : "",
      body_len : 0,
      http_version : null
    },
    response : {
      headers : {},
      status_code : null,
      body_len : 0,
      http_version : null
    },
    request_parser : new HTTPParser('request'),               //change here
    response_parser : new HTTPParser('response')      //change here
  };
```

This should solve an error which had to do with HTTPParser.REQUEST and HTTPParser.RESPONSE
Then in $YOURHOMEDIRECTORY/.node/.npm/websocket-server/VERSIONNUMBER/package/lib/_events.js I added the line

``` javascript
EventEmitter.prototype.emit = function(type) {
  if (type !== 'newListener' && (!this._events || !this._events[type]) &&
      this._bubbleTarget && this._bubbleTarget[type]) {
    this._bubbleTarget[type].emit.apply(this._bubbleTarget[type], arguments);
  } else {
    events.EventEmitter.prototype.setMaxListeners(0);              //added line
    events.EventEmitter.prototype.emit.apply(this, arguments);
  }
};
```

This one solved a problem with an possible EventEmitter Memory leak

Now when trying to run nodesheep-server.js I end up with this forever until I Ctrl-C 

```
Capturing packets on eth0
Listening on port 8181
```

Now after a while I got this error, but until now only once and at that point I was using netstat (even if it shouldnt do anything): 

```
Capturing packets on eth0
Listening on port 8181

http.js:1004
    abortError = new Error('http.ServerRequest timed out');
                 ^
RangeError: Maximum call stack size exceeded
```

This one really just appeared once, so I don't think it's relevant...

My chromesheep Icon say "Cannot connect to the server". Any ideas?

Chrome-Version: 17.0.963.46
JavaScript-Version: V8 3.8.9.5
Node.js-Version: 0.4.9-1ubuntu3
npm-Version: 0.2.19-1
node_pcap-Version: 0.3.0
node_websocket-server-Version: 1.4.04
node_htmlparser-Version: 1.7.4
node_json-Version: 0.2.10
node_events-Version: 0.3.0

Any other dependecies to get it running? As well node.js extension as other programs (eg. libpcap)

**Comment by ghost** [comment]
same issue

**Comment by ghost** [comment]
The error I recieve when google chrome is open states that the port is already in use. Therefore chromesheep saying "cannot connect to server" would indicate it cannot, because the server is occupied??

**Comment by hmarr** [comment]
Closing and archiving project (https://github.com/hmarr/chromesheep/issues/3#issuecomment-500624433)
