### ISSUE TITLE
cannot install pcap

### ISSUE THREAD

**Issue by SCBuergel** [hmarr/chromesheep#2]
I followed the instructions but cannot install the npm dependencies: `npm install pcap` fails miserably on my MacOS 10.11.6. 

Just FYI (installed via `brew install node`):
```
$ npm --version
5.0.3

$ node --version
v8.0.0
```

**Comment by k1epto** [comment]
I'm having the same problem on Windows 7, I cannot install pcap... please advise or fix your code to reflect current VStudio code... please

**Comment by hmarr** [comment]
Closing and archiving - see https://github.com/hmarr/chromesheep/issues/3#issuecomment-500624433
