### ISSUE TITLE
cannot install pcap on windows 7

### ISSUE THREAD

**Issue by k1epto** [hmarr/chromesheep#3]
All sorts of errors with every attempt... googled for hours to try and find a resolution, but no luck... please advise.

**Comment by hmarr** [comment]
I haven't worked on (or even used) this project in 8 years, so I'm afraid I can't help you with this. I'll mark the project as archived on GitHub to avoid further confusion.

If you're struggling to install pcap I'd perhaps try StackOverflow.

Sorry I can't be of more help, and good luck!
